### ISSUE TITLE
bash-interactive not found for aliases

### ISSUE THREAD

**Issue by clotodex** [cachix/devenv#1754]
**Describe the bug**

```zsh: /nix/store/bnwchlr4rlnrj4fn49zhxcyrlmf60hma-run-rust/bin/run-rust: bad interpreter: /nix/store/4k90qpzh1a4sldhnf7cxwkm9c0agq4fp-bash-interactive-5.2p37/bin/bash-interactive: no such file or directory```

This just started happening after a `devenv update` so might be some change in nixpkgs or 

**To reproduce**
In devenv nix, define any script, like
```
scripts.hello.exec = "echo hi";
```
and devenv.yaml
```
nixpkgs:
   url: 'github:NixOS/nixpkgs/master'
```

**Version**

devenv 1.4.1 (x86_64-linux)

**Comment by sandydoo** [comment]
nixpkgs changed the default bash to "interactive", which changed the `pname` of the derivation to `bash-interactive`.

I recently fixed a similar issue in devenv: https://github.com/cachix/devenv/pull/1745

I don't know what `run-rust` is though. Something in that wrapper script things that the executable name is the `pname` of the bash derivation.

**Comment by clotodex** [comment]
Yes that would be it - run-rust is just my script, replace it with `hello` from the example

**Comment by sandydoo** [comment]
Then a `devenv update devenv` should fix this for you.

**Comment by clotodex** [comment]
Sadly it did not - it updated the lock again but the error is still the same
I have devenv installed via nixos if that is relevant

**Comment by Yvaniak** [comment]
I had the same problem and setting scripts.hello.binary to "bash" did the trick for me.
If i understood correctly, it is due to [this](https://github.com/cachix/devenv/blob/6344ff303b0098afae94b28df8dc1b9b7ac1e227/src/modules/scripts.nix#L26) with the bashInteractive which is now the default.

**Comment by Yvaniak** [comment]
Oh, fixed now, I think by #1756

**Comment by mmlb** [comment]
Yep should be fixed by my PR, I had this same issue with scripts.

**Comment by sandydoo** [comment]
Ah, I forgot about the scripts. Thanks, @mmlb. 

Fixed in https://github.com/cachix/devenv/pull/1756.
