### ISSUE TITLE
Error when setting `pre-commit.settings.deadnix.fix` to true

### ISSUE THREAD

**Issue by jocelynthode** [cachix/devenv#86]
When setting: `pre-commit.settings.deadnix.fix = true` in devenv.nix I get an error everytime I enter my folder (direnv enabled).

```
direnv: loading ~/Projects/nixos-config/.envrc
Building shell ...
warning: applying 'toString' to path 'https://github.com/cachix/pre-commit-hooks.nix/blob/ebcbfe09d2bd6d15f68de3a0ebb1e4dcb5cd324b/modules/hooks.nix' and then accessing it is deprecated, at «stdin»:0
warning: applying 'toString' to path 'https://github.com/cachix/pre-commit-hooks.nix/blob/ebcbfe09d2bd6d15f68de3a0ebb1e4dcb5cd324b/modules/pre-commit.nix' and then accessing it is deprecated, at «stdin»:0
warning: applying 'toString' to path 'https://github.com/cachix/pre-commit-hooks.nix/blob/ebcbfe09d2bd6d15f68de3a0ebb1e4dcb5cd324b/modules/pre-commit.nix' and then accessing it is deprecated, at «stdin»:0
warning: applying 'toString' to path 'https://github.com/cachix/devenv/blob/59f9436834f819432b5c607238fc336345f19ab0/src/modules/pre-commit.nix' and then accessing it is deprecated, at «stdin»:0
error: attribute 'split' missing

       at https://github.com/cachix/pre-commit-hooks.nix/blob/ebcbfe09d2bd6d15f68de3a0ebb1e4dcb5cd324b/modules/hooks.nix:327:118:

          326|             let
          327|               toArg = string: "--" + (lib.concatMapStringsSep "-" lib.toLower (lib.filter (x: x != "") (lib.flatten (lib.split "([[:upper:]]+[[:lower:]]+)" string))));
             |                                                                                                                      ^
          328|               args = lib.concatMapStringsSep " " toArg (lib.filter (attr: settings.deadnix."${attr}") (lib.attrNames settings.deadnix));

       … while evaluating 'flatten'

       at https://github.com/NixOS/nixpkgs/blob/75f569b1a573c9736501981b1bd1808d30b37d3d/lib/lists.nix:138:13:

          137|   */
          138|   flatten = x:
             |             ^
          139|     if isList x

       … from call site
```

**Comment by domenkozar** [comment]
Fixed in https://github.com/cachix/pre-commit-hooks.nix, run `devenv update`  to fetch the fix :) Thanks for the report!

**Comment by jocelynthode** [comment]
Thanks for the lightning speed of the fix, it now works :)

**Comment by jocelynthode** [comment]
@domenkozar: Mmh still not working due to https://github.com/cachix/pre-commit-hooks.nix/issues/188 I have created a PR to fix this.
